spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: ${RABBIT_URL}
    port: 5672
    username: api-file-share
    password: api-file-share
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
logging:
  level:
    root: INFO
