package com.api.identity.enums;

public enum AuditAction {
    INVITATION_SENT,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,
    INVITATION_CANCELLED,
    MEMBER_JOINED,
    MEMBER_LEFT,
    MEMBER_REMOVED,
    OWNERSHIP_TRANSFERRED
}
